### ISSUE TITLE
Version 1

### ISSUE THREAD

**Issue by felixge** [hiroapp/cli#1]
# Plan

The goal for hiro v1 is to replace the current version of [quantastic](https://github.com/felixge/quantastic) which I'm using for local time tracking.
## Stories

| ? | As a | I want | So that |
| --- | --- | --- | --- |
| ✅ | User | to start new time entries | I can track what I'm currently working on |
| ✅ | User | to assign time entries to categories | I can analyze how I spent my time |
| ✅ | User | to list the time entries I created | I know that I recorded them correctly |
| ✅ | User | time zone information to be retained | I can understand my entries when traveling |
| ✅ | User | to be able to edit time entries | I can fix mistakes or add notes |
| ✅ | User | the system to automatically end the active entry when starting a new one | I can easily track different tasks |
| ✅ | User | to be able to end the currently active entry | I know how much time I've spent on it |
| ✅ | User | to be to delete time entries | I can fix mistakes |
| ✅ | User | to view monthly reports for a given category | I can invoice clients easily |
| ✅ | User | to be able to resume time entries | I can easily continue tracking where I left off |
| ❌ | User | the project to be documented | I can figure out how to use it |
| ❌ | Dev | the code to be tested and documented | I can understand it in the future and attract collaborators |
| ✅ | User | to view daily reports | I can see my progress |
| ❌ | User | to find the repo under hiro/cli | I'm not confused by the naming |
## Todo
- [x] Resume feature
- [x] Auto-edit last entry if no id is given
- [x] Delete feature
- [x] Monthly reports
- [ ] Refactor entry parsing
- [ ] Refactor common pkg
- [ ] Refactor template rendering
- [ ] Document coce base
